### ISSUE TITLE
Compilation error with Coq 8.9

### ISSUE THREAD

**Issue by clarus** [coq-contribs/quicksort-complexity#3]
Hi,

The 8.9 version of this package does not seem to work with Coq 8.9.1: https://coq-bench.github.io/clean/Linux-x86_64-4.07.1-2.0.1/released/8.9.1/quicksort-complexity/8.9.0.html
```
- coq_makefile -f Make -o Makefile.coq
- make -f Makefile.coq Makefile
- make[1]: Entering directory '/home/bench/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/coq-quicksort-complexity.8.9.0'
- COQDEP VFILES
- make[1]: Nothing to be done for 'Makefile'.
- make[1]: Leaving directory '/home/bench/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/coq-quicksort-complexity.8.9.0'
- make -f Makefile.coq all
- make[1]: Entering directory '/home/bench/.opam/ocaml-base-compiler.4.07.1/.opam-switch/build/coq-quicksort-complexity.8.9.0'
- COQC skip_list.v
- COQC nat_below.v
- COQC util.v
- COQC fix_measure_utils.v
- File "./nat_below.v", line 1, characters 0-38:
- Warning: Option Automatic Coercions Import is deprecated
- [deprecated-option,deprecated]
- File "./util.v", line 8, characters 9-18:
- Error:
- Syntax error: 'Type' or 'Types' expected after 'Implicit' (in [vernac:gallina_ext]).
```

@herbelin Do you think the tag should be updated?

**Comment by herbelin** [comment]
The tag is wrong since 2017 apparently. Can I safely update it or is there a risk that people depend it. Since the package is broken, I may suspect no, but shouldn't the normal policy to do something like a 8.9.0-1 tag?

**Comment by clarus** [comment]
OK. Yes indeed, I think that would be very pro to make a `8.9.0-1` tag so that the Git repository stays immutable.

**Comment by clarus** [comment]
Fixed by https://github.com/coq/opam-coq-archive/pull/1074
